var searchData=
[
  ['script_0',['Example: Adding a Command to Run a Script',['../md_docs_2CMAKE__COMMANDS.html#autotoc_md11',1,'']]],
  ['script_20command_1',['Example: Adding a Version Script Command',['../md_docs_2CMAKE__COMMANDS.html#autotoc_md10',1,'']]],
  ['scripts_2',['Scripts',['../md_README.html#autotoc_md108',1,'']]],
  ['scripts_20in_20evo_20crypter_3',['Scripts in evo-crypter',['../md_docs_2SCRIPTS.html',1,'']]],
  ['scripts_2emd_4',['SCRIPTS.md',['../SCRIPTS_8md.html',1,'']]],
  ['security_20considerations_20for_20evo_20crypter_5',['Security Considerations for evo-crypter',['../md_docs_2SECURITY.html',1,'']]],
  ['security_20enhancements_6',['Future Security Enhancements',['../md_docs_2SECURITY.html#autotoc_md73',1,'']]],
  ['security_2emd_7',['SECURITY.md',['../SECURITY_8md.html',1,'']]],
  ['semantic_20versioning_20semver_8',['Semantic Versioning (SemVer)',['../md_docs_2VERSIONING.html#autotoc_md91',1,'']]],
  ['semver_9',['Semantic Versioning (SemVer)',['../md_docs_2VERSIONING.html#autotoc_md91',1,'']]],
  ['sequence_10',['2. Generation Sequence',['../md_docs_2ALGORITHM.html#autotoc_md2',1,'']]],
  ['setup_11',['Setup',['../md_README.html#autotoc_md106',1,'']]],
  ['sh_20tt_12',['sh tt',['../md_docs_2SCRIPTS.html#autotoc_md66',1,'&lt;tt&gt;build.sh&lt;/tt&gt;'],['../md_docs_2SCRIPTS.html#autotoc_md67',1,'&lt;tt&gt;lint.sh&lt;/tt&gt;'],['../md_docs_2SCRIPTS.html#autotoc_md68',1,'&lt;tt&gt;test.sh&lt;/tt&gt;'],['../md_docs_2SCRIPTS.html#autotoc_md69',1,'&lt;tt&gt;update_version.sh&lt;/tt&gt;']]],
  ['short_5fname_13',['short_name',['../structFlagHandler.html#ad8cf1d154f30e924e7767ed9ba44558e',1,'FlagHandler']]],
  ['slithering_200_203_200_14',['Slithering (0.3.0)',['../md_docs_2ROADMAP.html#autotoc_md57',1,'']]],
  ['spaces_15',['6. Spaces',['../md_docs_2STYLEGUIDE.html#autotoc_md80',1,'']]],
  ['started_16',['started',['../md_docs_2CONTRIBUTING.html#autotoc_md15',1,'Getting Started'],['../md_README.html#autotoc_md104',1,'Getting Started']]],
  ['steps_20to_20add_20a_20new_20flag_17',['Steps to Add a New Flag',['../md_docs_2FLAGS.html#autotoc_md24',1,'']]],
  ['strategy_20for_20evo_20crypter_18',['Versioning Strategy for evo-crypter',['../md_docs_2VERSIONING.html',1,'']]],
  ['string_20or_20number_20flag_20e_20g_20tt_20output_20filename_20tt_20or_20tt_20level_20number_20tt_19',['2. String or Number Flag (e.g., &lt;tt&gt;--output &lt;filename&gt;&lt;/tt&gt; or &lt;tt&gt;--level &lt;number&gt;&lt;/tt&gt;)',['../md_docs_2FLAGS.html#autotoc_md27',1,'']]],
  ['structure_20',['Understanding the Structure',['../md_docs_2FLAGS.html#autotoc_md23',1,'']]],
  ['structure_20of_20tt_20add_5fcustom_5fcommand_20tt_21',['Basic Structure of &lt;tt&gt;add_custom_command&lt;/tt&gt;',['../md_docs_2CMAKE__COMMANDS.html#autotoc_md9',1,'']]],
  ['style_22',['12. Deviations from Linux Kernel Style',['../md_docs_2STYLEGUIDE.html#autotoc_md86',1,'']]],
  ['style_20guide_23',['Evo-Crypter Coding Style Guide',['../md_docs_2STYLEGUIDE.html',1,'']]],
  ['style_3a_24',['Overall Style:',['../md_docs_2PROJECT__IDENTITY.html#autotoc_md48',1,'']]],
  ['styleguide_2emd_25',['STYLEGUIDE.md',['../STYLEGUIDE_8md.html',1,'']]],
  ['sumar_26',['sumar',['../main_8c.html#ad2fc341d60a4e2d9598d41b04d4e513a',1,'main.c']]]
];
