var searchData=
[
  ['changelog_0',['CHANGELOG',['../md_CHANGELOG.html',1,'']]],
  ['changelog_2emd_1',['CHANGELOG.md',['../CHANGELOG_8md.html',1,'']]],
  ['checks_20yml_20tt_2',['checks yml tt',['../md_docs_2VERSIONING.html#autotoc_md96',1,'&lt;tt&gt;pr-checks.yml&lt;/tt&gt;'],['../md_docs_2VERSIONING.html#autotoc_md97',1,'&lt;tt&gt;push-checks.yml&lt;/tt&gt;']]],
  ['chunkprocessingargs_3',['ChunkProcessingArgs',['../structChunkProcessingArgs.html',1,'']]],
  ['cli_2ec_4',['cli.c',['../cli_8c.html',1,'']]],
  ['cli_2eh_5',['cli.h',['../cli_8h.html',1,'']]],
  ['cli_2eunit_2ec_6',['cli.unit.c',['../cli_8unit_8c.html',1,'']]],
  ['cmake_7',['Adding Custom Commands in CMake',['../md_docs_2CMAKE__COMMANDS.html',1,'']]],
  ['cmake_5fcommands_2emd_8',['CMAKE_COMMANDS.md',['../CMAKE__COMMANDS_8md.html',1,'']]],
  ['code_20integration_9',['14. VS Code Integration',['../md_docs_2STYLEGUIDE.html#autotoc_md88',1,'']]],
  ['code_20of_20conduct_10',['Code of Conduct',['../md_docs_2CONTRIBUTING.html#autotoc_md18',1,'']]],
  ['coding_20style_20guide_11',['Evo-Crypter Coding Style Guide',['../md_docs_2STYLEGUIDE.html',1,'']]],
  ['color_20palette_3a_12',['Color Palette:',['../md_docs_2PROJECT__IDENTITY.html#autotoc_md49',1,'']]],
  ['command_13',['Example: Adding a Version Script Command',['../md_docs_2CMAKE__COMMANDS.html#autotoc_md10',1,'']]],
  ['command_20line_20flags_20to_20evo_20crypter_14',['Adding New Command-Line Flags to evo-crypter',['../md_docs_2FLAGS.html',1,'']]],
  ['command_20to_20run_20a_20script_15',['Example: Adding a Command to Run a Script',['../md_docs_2CMAKE__COMMANDS.html#autotoc_md11',1,'']]],
  ['commands_16',['Why Use Custom Commands?',['../md_docs_2CMAKE__COMMANDS.html#autotoc_md8',1,'']]],
  ['commands_20in_20cmake_17',['Adding Custom Commands in CMake',['../md_docs_2CMAKE__COMMANDS.html',1,'']]],
  ['comments_18',['3. Comments',['../md_docs_2STYLEGUIDE.html#autotoc_md77',1,'']]],
  ['conclusion_19',['conclusion',['../md_docs_2FLAGS.html#autotoc_md30',1,'Conclusion'],['../md_docs_2CMAKE__COMMANDS.html#autotoc_md13',1,'Conclusion']]],
  ['conduct_20',['Code of Conduct',['../md_docs_2CONTRIBUTING.html#autotoc_md18',1,'']]],
  ['config_21',['Config',['../structConfig.html',1,'']]],
  ['considerations_20for_20evo_20crypter_22',['Security Considerations for evo-crypter',['../md_docs_2SECURITY.html',1,'']]],
  ['considered_3a_23',['Alternatives Considered:',['../md_docs_2PROJECT__IDENTITY.html#autotoc_md37',1,'']]],
  ['contributing_24',['Contributing',['../md_README.html#autotoc_md109',1,'']]],
  ['contributing_20to_20evo_20crypter_25',['Contributing to evo-crypter',['../md_docs_2CONTRIBUTING.html',1,'']]],
  ['contributing_20to_20other_20parts_20of_20the_20project_26',['Contributing to Other Parts of the Project',['../md_docs_2MUTATIONS.html#autotoc_md33',1,'']]],
  ['contributing_2emd_27',['CONTRIBUTING.md',['../CONTRIBUTING_8md.html',1,'']]],
  ['conventions_28',['4. Naming Conventions',['../md_docs_2STYLEGUIDE.html#autotoc_md78',1,'']]],
  ['core_20idea_3a_29',['Core Idea:',['../md_docs_2PROJECT__IDENTITY.html#autotoc_md44',1,'']]],
  ['crypter_30',['crypter',['../md_docs_2PROJECT__IDENTITY.html#autotoc_md35',1,'1. Name: Evo-Crypter'],['../md_docs_2FLAGS.html',1,'Adding New Command-Line Flags to evo-crypter'],['../md_docs_2ALGORITHM.html',1,'Algorithm Details for evo-crypter'],['../md_docs_2CONTRIBUTING.html',1,'Contributing to evo-crypter'],['../md_README.html',1,'evo-crypter'],['../md_docs_2PROJECT__IDENTITY.html',1,'Project Identity: Evo-Crypter'],['../md_docs_2ROADMAP.html',1,'Roadmap for evo-crypter'],['../md_docs_2SCRIPTS.html',1,'Scripts in evo-crypter'],['../md_docs_2SECURITY.html',1,'Security Considerations for evo-crypter'],['../md_docs_2VERSIONING.html',1,'Versioning Strategy for evo-crypter']]],
  ['crypter_20coding_20style_20guide_31',['Evo-Crypter Coding Style Guide',['../md_docs_2STYLEGUIDE.html',1,'']]],
  ['current_20ascii_20emoji_20unicode_20representation_3a_32',['Current ASCII &amp; Emoji/Unicode Representation:',['../md_docs_2PROJECT__IDENTITY.html#autotoc_md42',1,'']]],
  ['current_20limitations_33',['Current Limitations',['../md_docs_2SECURITY.html#autotoc_md71',1,'']]],
  ['custom_20commands_34',['Why Use Custom Commands?',['../md_docs_2CMAKE__COMMANDS.html#autotoc_md8',1,'']]],
  ['custom_20commands_20in_20cmake_35',['Adding Custom Commands in CMake',['../md_docs_2CMAKE__COMMANDS.html',1,'']]]
];
