var searchData=
[
  ['test_20sh_20tt_0',['&lt;tt&gt;test.sh&lt;/tt&gt;',['../md_docs_2SCRIPTS.html#autotoc_md68',1,'']]],
  ['testing_1',['Testing',['../md_docs_2FLAGS.html#autotoc_md29',1,'']]],
  ['the_20designer_2',['4. Visual Identity Guidelines (for the Designer)',['../md_docs_2PROJECT__IDENTITY.html#autotoc_md47',1,'']]],
  ['the_20project_3',['Contributing to Other Parts of the Project',['../md_docs_2MUTATIONS.html#autotoc_md33',1,'']]],
  ['the_20project_3a_4',['Representation in the Project:',['../md_docs_2PROJECT__IDENTITY.html#autotoc_md45',1,'']]],
  ['the_20structure_5',['Understanding the Structure',['../md_docs_2FLAGS.html#autotoc_md23',1,'']]],
  ['theme_6',['3. Evolutionary Theme',['../md_docs_2PROJECT__IDENTITY.html#autotoc_md43',1,'']]],
  ['threading_7',['5. Multi-threading',['../md_docs_2ALGORITHM.html#autotoc_md5',1,'']]],
  ['threads_8',['threads',['../structConfig.html#acca8518fb474236ff23870135c29d73d',1,'Config']]],
  ['tips_9',['Tips',['../md_docs_2CMAKE__COMMANDS.html#autotoc_md12',1,'']]],
  ['to_20add_20a_20new_20flag_10',['Steps to Add a New Flag',['../md_docs_2FLAGS.html#autotoc_md24',1,'']]],
  ['to_20evo_20crypter_11',['to evo crypter',['../md_docs_2FLAGS.html',1,'Adding New Command-Line Flags to evo-crypter'],['../md_docs_2CONTRIBUTING.html',1,'Contributing to evo-crypter']]],
  ['to_20other_20parts_20of_20the_20project_12',['Contributing to Other Parts of the Project',['../md_docs_2MUTATIONS.html#autotoc_md33',1,'']]],
  ['to_20run_20a_20script_13',['Example: Adding a Command to Run a Script',['../md_docs_2CMAKE__COMMANDS.html#autotoc_md11',1,'']]],
  ['tools_14',['11. Tools',['../md_docs_2STYLEGUIDE.html#autotoc_md85',1,'']]],
  ['tt_20add_5fcustom_5fcommand_20tt_15',['Basic Structure of &lt;tt&gt;add_custom_command&lt;/tt&gt;',['../md_docs_2CMAKE__COMMANDS.html#autotoc_md9',1,'']]],
  ['tt_20build_20sh_20tt_16',['&lt;tt&gt;build.sh&lt;/tt&gt;',['../md_docs_2SCRIPTS.html#autotoc_md66',1,'']]],
  ['tt_20exclude_20item1_20item2_20tt_17',['3. Array/List Flag (e.g., &lt;tt&gt;--exclude &lt;item1,item2,...&gt;&lt;/tt&gt;)',['../md_docs_2FLAGS.html#autotoc_md28',1,'']]],
  ['tt_20lint_20sh_20tt_18',['&lt;tt&gt;lint.sh&lt;/tt&gt;',['../md_docs_2SCRIPTS.html#autotoc_md67',1,'']]],
  ['tt_20main_20build_20yml_20tt_19',['&lt;tt&gt;main-build.yml&lt;/tt&gt;',['../md_docs_2VERSIONING.html#autotoc_md95',1,'']]],
  ['tt_20output_20filename_20tt_20or_20tt_20level_20number_20tt_20',['2. String or Number Flag (e.g., &lt;tt&gt;--output &lt;filename&gt;&lt;/tt&gt; or &lt;tt&gt;--level &lt;number&gt;&lt;/tt&gt;)',['../md_docs_2FLAGS.html#autotoc_md27',1,'']]],
  ['tt_20pr_20checks_20yml_20tt_21',['&lt;tt&gt;pr-checks.yml&lt;/tt&gt;',['../md_docs_2VERSIONING.html#autotoc_md96',1,'']]],
  ['tt_20push_20checks_20yml_20tt_22',['&lt;tt&gt;push-checks.yml&lt;/tt&gt;',['../md_docs_2VERSIONING.html#autotoc_md97',1,'']]],
  ['tt_20test_20sh_20tt_23',['&lt;tt&gt;test.sh&lt;/tt&gt;',['../md_docs_2SCRIPTS.html#autotoc_md68',1,'']]],
  ['tt_20update_20version_20yml_20tt_24',['&lt;tt&gt;update-version.yml&lt;/tt&gt;',['../md_docs_2VERSIONING.html#autotoc_md94',1,'']]],
  ['tt_20update_5fversion_20sh_20tt_25',['&lt;tt&gt;update_version.sh&lt;/tt&gt;',['../md_docs_2SCRIPTS.html#autotoc_md69',1,'']]],
  ['tt_20verbose_20tt_26',['1. Boolean Flag (e.g., &lt;tt&gt;--verbose&lt;/tt&gt;)',['../md_docs_2FLAGS.html#autotoc_md26',1,'']]]
];
