name: Update CHANGELOG

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Generate CHANGELOG
        id: changelog
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          changelog_filename: CHANGELOG.md
          config_file: .changelog-config.yml
          committer_username: "test"
          committer_email: "test@test.com"
          release_version: ${{ github.event.inputs.release_version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Integrate semantic versioning
        run: |
          echo "Here the action for semantic versioning will be integrated (Issue Automate Semantic Versioning on PR Merge #3)"

      - name: Commit updated CHANGELOG
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG.md [skip ci]" || echo "No changes to commit"
          git push
