name: Main Build and Release

on:
  push:
    paths:
      - '**/*.c'
      - '**/*.h'
    branches:
      - feat/set-up-gitHub-pages-for-project-documentation

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcmocka-dev clang clang-tidy clang-format cppcheck doxygen

      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile

      - name: Upload Docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
