name: Setup and deploy Github Pages

on:
  pull_request:
    types: [closed]
    branches: [ "main", "dev" ]
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/*.md'

jobs:
  build-and-release:
    name: Deploy github page
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Generate Doxygen Documentation
        id: generate-docs
        run: |
          doxygen Doxyfile 2> doxygen-errors.txt || true

      - name: Check for Doxygen errors
        id: check-errors
        run: |
          if [ -s doxygen-errors.txt ]; then
            echo "found_errors=true" >> $GITHUB_OUTPUT
            echo "errors<<EOF" >> $GITHUB_OUTPUT
            cat doxygen-errors.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "found_errors=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit errors in PR
        if: steps.check-errors.outputs.found_errors == 'true'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ### ⚠️ Errores al generar la documentación con Doxygen:
            ```
            ${{ steps.check-errors.outputs.errors }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ### ⚠️ Errores al generar la documentación con Doxygen:
            ```
            ${{ steps.check-errors.outputs.errors }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html

      - name: 📢 Show GitHub Pages URL
        run: |
          echo "📘 Here is the link: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
