name: Main Build and Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - '**/*.c'
      - '**/*.h'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ The PR was merged"

  build-and-release:
    if: github.event.pull_request.merged == true
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for git tag

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcmocka-dev clang clang-tidy clang-format cppcheck

      - name: Build project (Release)
        run: ./scripts/build.sh build Release

      - name: Get current version
        id: get_version
        run: |
          version=$(tr -d '\n' < version.txt)
          echo "Detected version: '$version'"
          echo "current_version=$version" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: ${{ success() }}
        with:
          tag_name: v${{ steps.get_version.outputs.current_version }}
          name: Release v${{ steps.get_version.outputs.current_version }}
          draft: false
          prerelease: false
          body: |
            ## Release v${{ steps.get_version.outputs.current_version }}
            This release includes the evo-crypter executable.
          files: |
            build/evo
