name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main", "dev", "**" ]

jobs:
  lint-test-build:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcmocka-dev clang clang-tidy clang-format cppcheck

      - name: Run linter
        run: ./scripts/lint.sh

      - name: Run tests
        run: ./scripts/test.sh

      - name: Build project (Debug)
        run: ./scripts/build.sh

  codeql-analysis:
    if: ${{ github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'dev' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
