name: PR Checks

on:
  push:
    branches: [ "main", "dev", "**" ]

jobs:
  lint-test-build:
    name: Lint, Test, and Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcmocka-dev clang clang-tidy clang-format cppcheck

      - name: Run linter
        run: ./scripts/lint.sh 2> lint-errors.txt || echo "found_lint_errors=true" >> $GITHUB_ENV

      - name: Build project (Debug) and Run tests
        run: ./scripts/test.sh 2> test-errors.txt || echo "found_test_errors=true" >> $GITHUB_ENV

      - name: Comment PR with errors
        if: env.found_lint_errors == 'true' || env.found_test_errors == 'true'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ## ❌ PR Checks Failed:
            ${{ env.found_lint_errors == 'true' && '### Linter Errors:\n```\n' + github.event.pull_request.head.sha + '\nCheck lint-errors.txt for details.\n```' }}
            ${{ env.found_test_errors == 'true' && '### Test Errors:\n```\n' + github.event.pull_request.head.sha + '\nCheck test-errors.txt for details.\n```' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  codeql-analysis:
    if: ${{ github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'dev' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"
