name: Push Checks

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  lint-test-build:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest
    steps:
      - name: Check for existing PRs
        id: check_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`
            });
            if (prs.data.length > 0) {
              core.setFailed('An open PR already exists for this branch. Skipping push checks.');
            }

      - name: Checkout code
        if: steps.check_pr.conclusion == 'success'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcmocka-dev clang clang-tidy clang-format cppcheck

      - name: Run linter
        if: steps.check_pr.conclusion == 'success'
        run: ./scripts/lint.sh

      - name: Run tests
        if: steps.check_pr.conclusion == 'success'
        run: ./scripts/test.sh

      - name: Build project (Debug)
        if: steps.check_pr.conclusion == 'success'
        run: ./scripts/build.sh
