name: Push Checks

on:
  push:
    branches-ignore:
      - main

jobs:
  lint-test-build:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcmocka-dev clang clang-tidy clang-format cppcheck

      - name: Run linter
        run: ./scripts/lint.sh

      - name: Run tests
        run: ./scripts/test.sh

      - name: Build project (Debug)
        run: ./scripts/build.sh

      - name: Get current version
        id: get_version
        run: echo "current_version=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Update patch version (feature or feat branches)
        if: startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/feat/')
        run: |
          ./scripts/update_version.sh $(echo "${{ steps.get_version.outputs.current_version }}" | awk -F. '{ $NF += 1; print }' OFS=".")
